############################################################
# INPUT
# Directory where the workflow exists
work_dir: "/scratch/gmichoud/Ramona_Nanopore/RIVERBacterialAssembly"

# Directory to save the output to
results_dir: "/scratch/gmichoud/Ramona_Nanopore/Results/"

# Directory for all the conda environments
env_dir: "/scratch/gmichoud/Ramona_Nanopore/RIVERBacterialAssembly/envs"

# Directory for Reads
reads_dir: "/scratch/gmichoud/Ramona_Nanopore/reads"

# Number of cpus or threads to use
threads: 28


##############################
# Parameters #
#genome_size: 6.5m

reads_size: 3000

checkm2_db : "/work/river/Databases/checkm2/CheckM2_database/uniref100.KO.1.dmnd"
bakta_db : "/work/river/Databases/Bakta2/db/"
