############################################################
# STEPS

# Steps to be done
steps: ["preprocessing"]
#, "whokaryote"] 


############################################################
# INPUT
# Directory where the workflow exists
work_dir: "/home/river/Desktop/Greg/MartinaGenomes/RIVERPacbioAssembly"

# Directory to save the output to
results_dir: "/home/river/Desktop/Greg/MartinaGenomes/Results"

# Directory for all the conda environments
env_dir: "/home/river/Desktop/Greg/MartinaGenomes/RIVERPacbioAssembly/envs"

# Directory for Reads
reads_dir: "/home/river/Desktop/Greg/MartinaGenomes/fastq_pass/barcode11"

# Number of cpus or threads to use
threads: 20


##############################
# Parameters #
subsample:
  genome_size: 3.5m

# get_length:
#   threads: 28
